server:
  port: 8080

spring:
  application:
    name: gateway
security:
  oauth2:
    client:
      provider:
        keycloak-gateway:
          issuer-uri: http://localhost:9090/realms/triwal-realm-dev
      registration:
        keycloak-gateway:
          client-id: triwal-gateway
          client-secret: siO1CZ3A6lodGpQb1dGAz5ncKezRcotX
          scope:
            - openid
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters: TokenRelay
      routes:
        - id: ms-transaction
          uri: http://ms-transaction
          predicates:
            - Path=/transaction/**
        - id: ms-user
          uri: http://ms-user
          predicates:
            - Path=/registration/**
      discovery:
        locator:
          enabled: true


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

