server:
  port: 8080

spring:
  application:
    name: gateway
security:
  oauth2:
    client:
      provider:
        keycloak-gateway:
          issuer-uri: http://localhost:9090/realms/triwal-realm-dev
      registration:
        keycloak-gateway:
          client-id: triwal-app
          client-secret: 2AW8lVZlq25DVBwI8UTLRYaK95bQsg9p
          scope:
            - openid
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/keycloak
  cloud:
    gateway:
      default-filters: TokenRelay
      routes:
        - id: ms-transaction
          uri: lb://ms-transaction
          predicates:
            - Path=/transaction/**
          filters:
            - StripPrefix=1
        - id: ms-user
          uri: lb://ms-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

